# Generated by Django 4.0.5 on 2022-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinturilloGraphql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
