# Generated by Django 4.0.5 on 2022-06-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinturilloGraphql', '0002_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinturilloGraphql.room'),
        ),
    ]
