# Generated by Django 4.0.5 on 2022-06-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinturilloGraphql', '0003_game_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(null=True, to='pinturilloGraphql.player'),
        ),
    ]
