# Generated by Django 4.0.5 on 2022-06-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinturilloGraphql', '0004_alter_room_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
    ]
